Fix c++ files to be pass syntax check; add c++ syntax check to pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -8,6 +8,18 @@ set -e
 trap 'echo "Error on line $LINENO: $BASH_COMMAND" >&2' ERR
 
 
+# Find all staged c++ files
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=d | grep -E '\.h$' || true)
+
+for FILE in $STAGED_FILES; do
+  clang++ -I./narf/narf/include/ -fsyntax-only $FILE 
+  if [ $? -ne 0 ]; then
+    echo "Syntax error in $FILE. Commit aborted."
+    exit 1
+  fi
+done
+
+
 # Find all staged YAML files
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=d | grep -E '\.ya?ml$' || true)
 
