Add check for json files in pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -33,6 +33,19 @@ for FILE in $STAGED_FILES_YAML; do
 done
 
 
+# Find all staged json files
+STAGED_FILES_JSON=$(git diff --cached --name-only --diff-filter=d | grep -E '\.ya?ml$' || true)
+
+# Check syntax of each json file
+for FILE in $STAGED_FILES_JSON; do
+  python -m json.tool $FILE > /dev/null
+  if [ $? -ne 0 ]; then
+    echo "Syntax error in $FILE. Commit aborted."
+    exit 1
+  fi
+done
+
+
 # Find all staged Python files
 STAGED_FILES_PY=$(git diff --cached --name-only --diff-filter=d | grep -E '\.py$' || true)
 
